# Generated by Django 6.0.4 on 2026-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediamap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediano', models.IntegerField(db_column='MEDIANO')),
                ('value', models.DecimalField(blank=True, db_column='VALUE', decimal_places=0, max_digits=12, null=True)),
            ],
            options={
                'db_table': '[EVASAPP].[MEDIAMAP]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientno', models.IntegerField(db_column='CLIENTNO')),
                ('gloryid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GLORYID', max_length=30)),
                ('startcash', models.IntegerField(db_column='STARTCASH')),
                ('usamt', models.DecimalField(db_column='USAMT', decimal_places=0, max_digits=14)),
                ('cashamt', models.DecimalField(db_column='CASHAMT', decimal_places=0, max_digits=14)),
                ('siteno', models.IntegerField(blank=True, db_column='SITENO', null=True)),
                ('lasttrace', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LASTTRACE', max_length=20, null=True)),
                ('traceversion', models.IntegerField(db_column='TRACEVERSION')),
            ],
            options={
                'db_table': '[EVASAPP].[INVENTORY_V]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventorydtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientno', models.IntegerField(db_column='CLIENTNO')),
                ('gloryid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GLORYID', max_length=30)),
                ('startcash', models.IntegerField(db_column='STARTCASH')),
                ('looseflg', models.IntegerField(db_column='LOOSEFLG')),
                ('mediano', models.IntegerField(db_column='MEDIANO')),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=0, max_digits=18)),
                ('siteno', models.IntegerField(blank=True, db_column='SITENO', null=True)),
                ('traceversion', models.IntegerField(db_column='TRACEVERSION')),
                ('lasttrace', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LASTTRACE', max_length=20, null=True)),
            ],
            options={
                'db_table': '[EVASAPP].[INVENTORYDTL_V]',
                'managed': False,
            },
        ),
    ]
